server:
  port: 8989

baseUrl:
  user-service: "http://user-service:8081"

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthenticationFilter
        - id: task-service
          uri: http://task-service:8082
          predicates:
            - Path=/tasks/**
          filters:
            - JwtAuthenticationFilter